import {Inter} from "next/font/google";
import {ToastContainer, toast} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Our Farmer",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        <ToastContainer/>
        </body>
        </html>
    );
}
